find_program(CLANG_FORMAT NAMES clang-format HINTS /opt/homebrew/opt/llvm/bin)
file(GLOB OWNED_CPP CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/src/*.cpp" "${PROJECT_SOURCE_DIR}/src/*.hpp" "${PROJECT_SOURCE_DIR}/tests/*.cpp")
if(CLANG_FORMAT)
  execute_process(COMMAND ${CLANG_FORMAT} --version OUTPUT_VARIABLE FORMAT_VERSION)
  if(NOT FORMAT_VERSION MATCHES "version 23[.]1[.]0")
    message(FATAL_ERROR "Install clang-format 23.1.0 (python -m pip install clang-format==23.1.0)")
  endif()
  add_custom_target(format COMMAND ${CLANG_FORMAT} -i ${OWNED_CPP} VERBATIM)
  add_custom_target(format-check COMMAND ${CLANG_FORMAT} --dry-run --Werror ${OWNED_CPP} VERBATIM)
else()
  message(STATUS "Install clang-format 23.1.0 to enable format and format-check")
endif()
